version: "3.7"
services:
  app:
    build: .
    image: rpi-timelapse:latest
    devices:
      - "/dev/vchiq:/dev/vchiq"
    volumes:
      # for local storage
      - type: volume
        source: rpi-timelapse-vol
        target: /timelapse
      # for AWS credentials
#     - type: bind
#       source: ${HOME}/.aws/credentials
#       target: /root/.aws/credentials
#       read_only: true
#     - type: bind
#       source: ${HOME}/.aws/config
#       target: /root/.aws/config
#       read_only: true
    restart: always
    command: app
volumes:
  rpi-timelapse-vol:
